// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbi/service.proto

package pbi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	pb "proto.test/pb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchRequest struct {
	Node                 *pb.Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_487ef7b598cf0cc7, []int{0}
}

func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

func (m *FetchRequest) GetNode() *pb.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type FetchResponse struct {
	Node                 *pb.Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchResponse) Reset()         { *m = FetchResponse{} }
func (m *FetchResponse) String() string { return proto.CompactTextString(m) }
func (*FetchResponse) ProtoMessage()    {}
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_487ef7b598cf0cc7, []int{1}
}

func (m *FetchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchResponse.Unmarshal(m, b)
}
func (m *FetchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchResponse.Marshal(b, m, deterministic)
}
func (m *FetchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchResponse.Merge(m, src)
}
func (m *FetchResponse) XXX_Size() int {
	return xxx_messageInfo_FetchResponse.Size(m)
}
func (m *FetchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchResponse proto.InternalMessageInfo

func (m *FetchResponse) GetNode() *pb.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *FetchResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_487ef7b598cf0cc7, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*FetchRequest)(nil), "pb.FetchRequest")
	proto.RegisterType((*FetchResponse)(nil), "pb.FetchResponse")
	proto.RegisterType((*Error)(nil), "pb.Error")
}

func init() { proto.RegisterFile("pbi/service.proto", fileDescriptor_487ef7b598cf0cc7) }

var fileDescriptor_487ef7b598cf0cc7 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x41, 0x4b, 0x85, 0x40,
	0x14, 0x85, 0x79, 0x8f, 0x67, 0x2f, 0x6f, 0xbd, 0xd0, 0xbb, 0x12, 0x09, 0x0a, 0x57, 0x2d, 0x64,
	0x04, 0x23, 0xda, 0x07, 0xb5, 0x34, 0x98, 0x65, 0x3b, 0x47, 0x2f, 0x25, 0x94, 0x33, 0xcd, 0x4c,
	0x42, 0xff, 0x3e, 0xe6, 0xaa, 0xe0, 0xaa, 0xdd, 0x9c, 0xef, 0xdc, 0x39, 0x9c, 0x03, 0xa9, 0x51,
	0x43, 0xe5, 0xc8, 0x4e, 0x43, 0x47, 0xc2, 0x58, 0xed, 0x35, 0xee, 0x8d, 0xca, 0x4f, 0x46, 0x55,
	0xa3, 0xee, 0x17, 0x54, 0x94, 0x70, 0xf9, 0x42, 0xbe, 0xfb, 0x90, 0xf4, 0xfd, 0x43, 0xce, 0xe3,
	0x35, 0x1c, 0x82, 0x9b, 0xed, 0x6e, 0x77, 0x77, 0x17, 0xf5, 0xb9, 0x30, 0x4a, 0x34, 0xba, 0x27,
	0xc9, 0xb4, 0x68, 0xe0, 0xb4, 0x5c, 0x3b, 0xa3, 0x47, 0x47, 0xff, 0x9f, 0xe3, 0x0d, 0x44, 0x64,
	0xad, 0xb6, 0xd9, 0x9e, 0xed, 0x38, 0xd8, 0xcf, 0x01, 0xc8, 0x99, 0x17, 0x0f, 0x10, 0xb1, 0x46,
	0x84, 0x43, 0xb7, 0xe6, 0xc4, 0x92, 0xdf, 0x98, 0xc1, 0xf1, 0x8b, 0x9c, 0x6b, 0xdf, 0x89, 0xff,
	0xc7, 0x72, 0x95, 0xf5, 0x23, 0x1c, 0x5f, 0x27, 0xb2, 0x9f, 0xed, 0x2f, 0x96, 0x10, 0x71, 0x23,
	0x4c, 0x42, 0xf8, 0x76, 0x4a, 0x9e, 0x6e, 0xc8, 0x5c, 0xf7, 0x29, 0x79, 0xbb, 0xe2, 0xd9, 0xc2,
	0x93, 0xf3, 0x95, 0x51, 0x83, 0x3a, 0x63, 0x7d, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xae,
	0xa4, 0x54, 0x2e, 0x01, 0x00, 0x00,
}
